### PR TITLE
Correcting minor typos

### PR DESCRIPTION
**Pull request by PabloValarezo**
Just correcting a few minor typos. Great guide. Thx

### CODE REVIEW

**Comment by JacobDWaters** [comment]
@PabloValarezo thank you for catching those!

**Comment by alexc307** [comment]
Hey guys - thank you so much for putting this together, it is really appreciated. On the Okta create groups/rules flow I believe there might be a missing step, the one where you create the actual group. Would you mind attaching that part also?

Much appreciated. 

https://github.com/JacobDWaters/Okta-Workflows/tree/main/Okta/Create%20group%20and%20group%20rules%20from%20profile%20changes

**Comment by JacobDWaters** [comment]
@alexc307 hmm, that wouldn't be very helpful if thats the case.

If you open up the flow and go to the end, you should see an `if/else` card with "save" showing. hit save. The conditional actions should now show. In those conditional actions should be a create group, create group rule, and activate group rule cards. Let me know if theyre missing for any reason and i'll try figure out why.

**Comment by alexc307** [comment]
Apologies, maybe it's me but I am not seeing any if/else card, nor the
flowpack per se (if the intention was for that to be there). It's not an
emergency, it's Friday for everyone after all, but when you have a chance I
would appreciate any help you could offer. Thanks again.

**Comment by JacobDWaters** [comment]
Hmm, the flowpack (in this case .folder file) [should be here](https://github.com/JacobDWaters/Okta-Workflows/blob/main/Okta/Create%20group%20and%20group%20rules%20from%20profile%20changes/createGroupAndGroupRulesFromProfileChanges.folder). 

When you import the .folder file there should be one flow and table contained within.

Attached it as a zip too. Can unzip and import.
[createGroupAndGroupRulesFromProfileChanges.folder.zip](https://github.com/JacobDWaters/Okta-Workflows/files/9385844/createGroupAndGroupRulesFromProfileChanges.folder.zip)

**Comment by alexc307** [comment]
Ok, just as I thought, it was me al along....duuh

Thank you very much.

**Pull request merged**
